public class MathOperations {
    
    public static String name = 'Addition opp';
    public Integer num = 33;//non static
    
    public static Integer add(Integer a, Integer b){
        
        return a + b;
    }
    public static Double add(Double a, Double b){
       
        return a+b;
    }
    public static Integer add(Integer a, Integer b, Integer c){
        return a+b+c;
    }
    
    public static Double add(Integer a, Double b){
        return a+b;
        
    }
    
    public static Double add(Double a, Integer b){
        return a+b;
    }
}